stages:
  - deploy

variables:
  DEPLOY_DIR: "/home/ubuntu/deployed/hat-site-testnet/"


deploy:
  stage: deploy
  script:
    - pwd
    - whoami
    - mkdir -p $DEPLOY_DIR
    - cp -r * $DEPLOY_DIR
    - cd $DEPLOY_DIR
    - pwd
    - npm install
    - CI=false npm run build
    - pkill -f node || true
    - npm run start >> hat-site.log 2>&1&
  only:
    - master
  tags:
    - hat-site