stages:
  - deploy

variables:
  DEPLOY_DIR: "/home/ubuntu/deployed/hat-site-testnet/"


deploy:
  stage: deploy
  script:
    - pwd
    - whoami
    - export $(grep -v '^#' /etc/hat-site/config.ini | tr --delete '"' | xargs -d '\n')
    - echo ${SSL_CERT}
    - echo ${SSL_KEY}
    - mkdir -p $DEPLOY_DIR
    - cp -r * $DEPLOY_DIR
    - cd $DEPLOY_DIR
    - pwd
    - npm install
    - CI=false npm run build
    - pkill -f serve || true
    - sudo serve -s build --listen 443 --ssl-cert $SSL_CERT --ssl-key $SSL_KEY > /dev/null 2>&1 &
  only:
    - ci-test
  tags:
    - hat-site